all: main_ui.py word_edit_ui.py devices_ui.py
	

main_ui.py: main.ui
	pyuic4 -o main_ui.py main.ui

word_edit_ui.py: word_edit.ui
	pyuic4 -o word_edit_ui.py word_edit.ui

devices_ui.py: devices.ui
	pyuic4 -o devices_ui.py devices.ui
